### ISSUE TITLE
Mismatches between VCF and reference sequence

### ISSUE THREAD

**Issue by ahwanpandey** [steverozen/ICAMS#1]
Hello,

Thanks for this package. I have been using for a while now, but recently, since I updated to ICAMS_2.0.10, I have been getting these errors when using `MutectVCFFilesToCatalog`

```
Error in AnnotateIDVCF(ID, ref.genome = ref.genome) : 
  Mismatches between VCF and reference sequence; see file.csv
```

The files (for each error per VCF) contains these regions:

VCF1

  | df.CHROM | df.POS | df.REF | df.ALT | df.seq.context | seq.to.check
-- | -- | -- | -- | -- | -- | --
387 | 4 | 45949414 | TAA | TA | AAAAAATAAAAAAA | TA

VCF2

  | df.CHROM | df.POS | df.REF | df.ALT | df.seq.context | seq.to.check
-- | -- | -- | -- | -- | -- | --
567 | 10 | 42610153 | TTTTTA | TTTTTATTTTATTTTA | ATATAGGAAGGATAGCTGCAAATATACCTGACACACTTATCTGTGAGTATGGTGGTAGCATTTTTATTTTATTTTATTTTATTTTTGAGAGAGGGTCTCACTTTGTCACCCAAGATGGAGT | T

VCF3

  | df.CHROM | df.POS | df.REF | df.ALT | df.seq.context | seq.to.check
-- | -- | -- | -- | -- | -- | --
567 | 10 | 42610153 | TTTTTA | TTTTTATTTTATTTTA | ATATAGGAAGGATAGCTGCAAATATACCTGACACACTTATCTGTGAGTATGGTGGTAGCATTTTTATTTTATTTTATTTTATTTTTGAGAGAGGGTCTCACTTTGTCACCCAAGATGGAGT | T

VCF4

  | df.CHROM | df.POS | df.REF | df.ALT | df.seq.context | seq.to.check
-- | -- | -- | -- | -- | -- | --
122 | 2 | 88687772 | GT | GTT | TGAGGTGTTTTTT | G

VCF5

  | df.CHROM | df.POS | df.REF | df.ALT | df.seq.context | seq.to.check
-- | -- | -- | -- | -- | -- | --
154 | 2 | 1.64E+08 | GTATATATATA | GTA | ATATATATATTTTATATATATATATATTTCTGACGTGTGTGTGTGTGTGTATATATATATATATATATATATATATATATATATATACACAATGTATATTAGATG | GTATATATA
593 | 8 | 37932474 | CCTATATAC | CTATCTATATAC | ATATATACTATATATATACCTATATACTATATATACT | C

This does not happen with all my VCFs, but most of them. They have been processed with the same pipeline. Is there a way the user can disable this check for indels? I feel these regions are complex repeats and since they are not that many, they can be safely ignored.

I could also revert back to an older version if the changes are not that significant and would produce similar results?

Thanks for your help and this awesome tool!

Ahwan

**Comment by ahwanpandey** [comment]
I see there is a flag.mismatches option that should take care of this?

`AnnotateIDVCF <- function(ID.vcf, ref.genome, flag.mismatches = 0)`

But this is not visible from `MutectVCFFilesToCatalog` :(

**Comment by jnh01** [comment]
@ahwanpandey 
Thanks a lot for your detailed description of the problem. We have added an optional argument `flag.mismatches` in function `MutectVCFFilesToCatalog` and other exported functions which call `AnnotateIDVCF`. 

Please refer to the updated reference manual for more details: https://github.com/steverozen/ICAMS/blob/v2.0.10-branch/data-raw/ICAMS_2.0.10.9001.pdf

The changes have been pushed to GitHub and you may download the updated ICAMS:
`devtools::install_github(repo = "steverozen/ICAMS", ref = "v2.0.10-branch")`

If you have other suggestion about this package, please let us know. Thanks!

**Comment by ahwanpandey** [comment]
@jnh01 
thanks for the quick fix! Things seem to be working like before now!
