### ISSUE TITLE
Question: possible to get context/category sssignment of each mutation in VCF?

### ISSUE THREAD

**Issue by ahwanpandey** [steverozen/ICAMS#3]
Good morning,

I was wondering if there was a way to get the assignment of each mutation in the VCF to the signature context? Foe example for a few lines of the VCF as follows:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SampleID
1	60868313	.	AAG	A	.	PASS	.	GT:AD:AF:DP	0/1:58,22:0.275:80
1	110005445	.	CAA	C	.	PASS	.	GT:AD:AF:DP	0/1:24,19:0.442:55
1	235268805	.	TAA	T	.	PASS	.	GT:AD:AF:DP	0/1:39,35:0.473:116
2	22105991	.	CAT	C	.	PASS	.	GT:AD:AF:DP	0/1:10,13:0.565:27
```

Could ICAMs return something that contains the context assigned for each mutation such that it could be concatenated to a table? eg..

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SampleID    ICAMS_context
1	60868313	.	AAG	A	.	PASS	.	GT:AD:AF:DP	0/1:58,22:0.275:80    DEL:repeats:2:5+
1	110005445	.	CAA	C	.	PASS	.	GT:AD:AF:DP	0/1:24,19:0.442:55    DEL:repeats:2:5+
1	235268805	.	TAA	T	.	PASS	.	GT:AD:AF:DP	0/1:39,35:0.473:116    DEL:repeats:2:5+
2	22105991	.	CAT	C	.	PASS	.	GT:AD:AF:DP	0/1:10,13:0.565:27    DEL:repeats:2:5+
```

This would be really helpful to an already awesome package.

Thanks,
Ahwan

**Comment by jnh01** [comment]
@ahwanpandey 
Thanks a lot for your suggestion. We have updated functions `MutectVCFFilesToCatalog`, `MutectVCFFilesToCatalogAndPlotToPdf` and `MutectVCFFilesToZipFile` such that object `catID` from the returned list has been changed from an ID catalog to a **list**: the second element `annotated.vcfs` is a list of data frames which contain the original VCF ID mutation rows with three additional columns `seq.context.width`, `seq.context` and `ID.class` added. You can get category assignment of each ID mutation in VCF from `ID.class` column.

The returned value from functions `StrelkaIDVCFFilesToCatalog`, `StrelkaIDVCFFilesToCatalogAndPlotToPdf`, `StrelkaIDVCFFilesToZipFile` and `VCFsToIDCatalogs` also contain the ID category assignment information. You may refer to the updated reference manual with link provided on [README.md](https://github.com/steverozen/ICAMS/blob/master/README.md) for more details.

Please install the latest ICAMS development version 2.1.2.9005 from GitHub master branch with installation methods listed on [README.md](https://github.com/steverozen/ICAMS/blob/master/README.md).

If you have other suggestion about this package or find any bug, please let us know. Thanks!

**Comment by ahwanpandey** [comment]
Thanks @jnh01 for the prompt response and the solution!
