### ISSUE TITLE
MutectVCFFilesToCatalog function change

### ISSUE THREAD

**Issue by ahwanpandey** [steverozen/ICAMS#4]
Good morning,

I used to be able to read most properly formatted VCF files using the MutectVCFFilesToCatalog with no issues. An example VCF is:

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SampleID
1	14815	.	C	T	.	PASS	.	GT:AD:AF:DP	0/1:185,20:0.098:206
1	127575	.	T	C	.	PASS	.	GT:AD:AF:DP	0/1:105,22:0.173:127
1	534324	.	G	T	.	PASS	.	GT:AD:AF:DP	0/1:129,34:0.209:164
1	534861	.	AT	A	.	PASS	.	GT:AD:AF:DP	0/1:75,5:0.062:80
etc...
```
But the newest release seems to have put into place a different check and hence I can't process the same VCFs I used to be able to with ICAMS any longer.

```
type1 <- c("F1R2", "F2R1")
  type2 <- c("REF_F1R2", "ALT_F1R2", "REF_F2R1", "ALT_F2R1")
  if (!all(sapply(type1, FUN = grepl, x = vcf$FORMAT[1])) && 
    !all(sapply(type2, FUN = grepl, x = vcf$FORMAT[1]))) {
    stop("\nVCF ", ifelse(is.null(name.of.VCF), "", dQuote(name.of.VCF)), 
      " does not appear to be a Mutect VCF, please check the data")
  }
```

The old check of the VCF seemed much simpler:

```
if (!any(grepl("/1", unlist(vcf[1, ]), fixed = TRUE)) && 
      !any(grepl("|1", unlist(vcf[1, ]), fixed = TRUE))) {
    stop("\nVCF ", ifelse(is.null(name.of.VCF), "", dQuote(name.of.VCF)),
         " does not appear to be a Mutect VCF, please check the data")
  }
```

Is there a possibility to include a new method to read such generic VCFs? Or have a method that brings back the old way of processing the VCFs?

Thanks!

**Comment by ahwanpandey** [comment]
The version not working for me anymore is "ICAMS_2.1.2.9011"

I was using "ICAMS_2.0.10.9001" with no issues previously

**Comment by jnh01** [comment]
@ahwanpandey 
Many thanks for providing the sample VCF. It is a good idea to develop new functions to read generic VCFs. 

May I know for the VCFs you have, do they have DBS inside? Because for Strelka VCFs, you will need to split SBS into DBS according to the VAFs (variant allele frequencies). That is why in ICAMS we are trying to calculate VAFs for each variant.

**Comment by ahwanpandey** [comment]
@jnh01 

Thanks so much for you e-mail. I have placed a full test VCF for you here.
https://www.dropbox.com/sh/z7rcokj6j3xgged/AACce2xrCGRxfv38TVW4wU-ea?dl=0

This tumor somatic VCF is from a Tumor/Normal analysis  generated by merging the calls of 4 callers (Mutect2, VarDict, Varscan2 and Strelka2) using GATK's CombineVariants. The VCFs were first split for multi-allelics and left trimmed using vt before combining. The merged VCF was then annotated and simplified a bit using custom scripts. It has already been filtered for just PASS variants using various criteria. VCFs generated this way have no issues being read and processed  using "ICAMS_2.0.10.9001" (except in rare cases where a genotype was not called for the first record in the VCF i.e. ./.). It would be nice to be able to skip this first line check because I have been manually genotyping these rare cases to be able to be read by ICAMS. Maybe a option for just a warning?

Another neat feature would be the ability to read a table that just has "#CHROM", "POS", "REF" and "ALT" columns.

Thanks for your consideration for these features! ICAMS is a brilliant tool.

**Comment by jnh01** [comment]
@ahwanpandey 
Thanks a lot for providing the sample VCF and additional details how this VCF was generated. 

I have temporarily changed the function [`GetMutectVAF`](https://github.com/steverozen/ICAMS/blob/74757a3af66a6539317fa0e3c17971bd52f4608b/R/VCF_to_catalog_functions.R#L373) to raise a warning instead of an error when the VCF seems not like a Mutect VCF. You can try to install the latest ICAMS from GitHub to process your generic VCFs.

There is an internal function `ICAMS:::MakeDataFrameFromVCF` that can read a **tab-delimited** file that just has "#CHROM", "POS", "REF" and "ALT" columns. This is actually a generic function which can read in data lines from various types of VCF(strelka, mutect...) to a data frame. It will also work when the input file does not have meta-information lines that start with ##

We will try to develop new functions reading and processing generic VCFs. The key consideration is the interface design, as we would also want it to be compatible with Strelka and Mutect VCFs. So it may take some time, we will update you again once we finish this task.

Meanwhile, if you find any bug or have other suggestion about this package, please let us know. Thanks!

**Comment by ahwanpandey** [comment]
Hi @jnh01 

Thanks for updating the git. I am able to read all the VCFs as before now.

However, there is a new issue now. 

The indel catalogue seems to be a different type than before (the last command in the script below i.e. for catID)
```
test_catalogue = MutectVCFFilesToCatalog(sample_info$FILTERED_VCF[1], 
                                         ref.genome = "hg19", region = "genome", 
                                         flag.mismatches = 1, names.of.VCFs = sample_info$SampleID[1])

> data.table("Name" = row.names(test_catalogue$catSBS96), test_catalogue$catSBS96) %>% head()
   Name test_sample
1: ACAA          150
2: ACCA          102
3: ACGA           18
4: ACTA          102
5: CCAA          111
6: CCCA          107
> data.table("Name" = row.names(test_catalogue$catSBS1536), test_catalogue$catSBS1536) %>% head()
     Name test_sample
1: AACAAA           28
2: AACACA            5
3: AACAGA           10
4: AACATA            8
5: AACCAA           14
6: AACCCA           13
> data.table("Name" = row.names(test_catalogue$catDBS78), test_catalogue$catDBS78) %>% head()
   Name test_sample
1: ACCA            0
2: ACCG            0
3: ACCT            1
4: ACGA            3
5: ACGG            1
6: ACGT            2
> data.table("Name" = row.names(test_catalogue$catDBS136), test_catalogue$catDBS136) %>% head()
   Name test_sample
1: AACA            1
2: AACC            0
3: AACG            0
4: AACT            0
5: AATA            0
6: AATC            0
> data.table("Name" = row.names(test_catalogue$catID), test_catalogue$catID) %>% head()
                      V1
1: 25,27, 8, 3, 2,11,...
2:                <list>
3:                <list>
> 
```

I can only convert the indel catalogue to a table if I pull it like this:
```
> data.table("Name" = row.names(test_catalogue$catID$catalog), test_catalogue$catID$catalog) %>% head()
         Name test_sample
1:  DEL:C:1:0           25
2:  DEL:C:1:1           27
3:  DEL:C:1:2            8
4:  DEL:C:1:3            3
5:  DEL:C:1:4            2
6: DEL:C:1:5+           11
```

TransformCatalog also seems to not be working with either ```test_catalogue$catID``` or ```test_catalogue$catID$catalog```
```
> TransformCatalog(test_catalogue$catID, target.ref.genome = "hg19", target.region = "genome", target.catalog.type = "counts.signature")
Error in CheckCatalogAttributes(catalog) : 
  Cannot perform transformation from a catalog with NULL catalog.type

> TransformCatalog(test_catalogue$catID$catalog, target.ref.genome = "hg19", target.region = "genome", target.catalog.type = "counts.signature")
Error in CheckCatalogAttributes(catalog) : 
  Cannot perform transformation from a catalog with NULL abundance
```

The indel catalogue being returned is now a different type to the other catalogues:
![image](https://user-images.githubusercontent.com/8450532/87630321-2e005c80-c778-11ea-809f-526cf563753f.png)

Not sure if this is on purpose, is there some other way I need to be using ```TransformCatalog``` on indels now?

Thanks!

**Comment by ahwanpandey** [comment]
Seems like this issue arises because of the update from  a previous issue I posted?

https://github.com/steverozen/ICAMS/issues/3

In that issue, I actually was referring to all the types of variants and not just for indels. It just so happened my example VCF just had indels!

It'd be great to have all the catalogues returned as a list with the ```*.class``` column, and also be able to use ```TransformCatalog```. So far this is the only method that I am using that has issues with the list type return. ```PlotCatalogToPdf```  also works fine with ```test_catalogue$catID$catalog```

**Comment by jnh01** [comment]
Hi @ahwanpandey 

Really sorry for the late reply. We have enabled returning the annotated VCF with the `*.class` column for all types of variants. To be backward compatible with the previous CRAN release (v2.1.2), you can get the list `annotated.vcfs` from the return value by specifying argument `return.annotated.vcfs` = TRUE in `MutectVCFFilesToCatalog` and other functions generating catalogs. 

`TransformCatalog` has also been updated to enable "counts" -> "counts.signature" catalog transformation when the source catalog has NULL abundance.

Pertaining to a previous issue #1 , you can get the list `discarded.variants` in the return value  if there are variants that were excluded in the analysis. Please refer to the documentation of return value in `MutectVCFFilesToCatalog` for the various types of discarded variants. A new argument `suppress.discarded.variants.warnings` with default value TRUE has been added to suppress warning messages showing information about the discarded variants. 

We have also improved time performance for functions generating catalogs by optimising some of the code. You can refer to [NEWS.md](https://github.com/steverozen/ICAMS/blob/master/NEWS.md) for the updates of the latest stable version on GitHub master branch.

Thanks a lot for your previous suggestions. If you find any bug or have other suggestion about this package, please let us know!

**Comment by jnh01** [comment]
@ahwanpandey 

Sorry for replying so late. Regarding your suggestions previously, 
> Is there a possibility to include a new method to read such generic VCFs? 

> Another neat feature would be the ability to read a table that just has "#CHROM", "POS", "REF" and "ALT" columns.

we have completed developing a new wrapper function `VCFsToCatalogs` to process VCFs from different variant callers or just tables with the necessary columns ("#CHROM", "POS", "REF" and "ALT"). This is backward compatible with the previous catalog generating functions like `MutectVCFFilesToCatalog`. You can specify `variant.caller` = "mutect" to process Mutect VCFs. It can also process Strelka VCFs by specifying `variant.caller` = "strelka". 

For reading generic VCFs/tables in your case, you can use `VCFsToCatalogs` specifying `variant.caller` = "unknown". One thing to take note is that if `variant.caller` = "unknown", `VCFsToCatalogs` by default will not merge adjacent SBSs as DBS according to  VAFs (variant allele frequencies). The default value for new `VAF` and `read.depth` columns after reading in generic VCFs/tables are all NAs. So you may get all zero mutation counts in DBS catalogs from the output.

If you want to merge adjacent SBSs as DBS according to VAFs for your generic VCFs/tables, you can write your own calculating VAF function(e.g. [`GetConsensusVAF`](https://github.com/steverozen/ICAMS/blob/3b466b0148c3dd880c15df8875fc8c593d4e2863/R/VCF_to_catalog_functions.R#L499)) and pass to the argument `get.vaf.function` in `VCFsToCatalogs` (Your own function should add two additional columns `VAF` and `read.depth` to the original VCF/table). You can also pass optional arguments to `get.vaf.function`. 

If VAFs are calculated for generic VCFs/tables,  ICAMS will merge adjacent SBSs into DBS if their VAF difference is less than 0.02 by default (See [`SplitSBSVCF`](https://github.com/steverozen/ICAMS/blob/3b466b0148c3dd880c15df8875fc8c593d4e2863/R/VCF_to_catalog_functions.R#L965) for more details). You can modify this threshold value by changing the argument `max.vaf.diff` in function `VCFsToCatalogs`.

Another new feature for `VCFsToCatalogs` is that you can turn on parallel computing if you have many VCFs/tables to process by specifying the additional argument `num.of.cores`. We also optimized some of the code, so reading in millions of lines from a VCF/table is now much faster compared to previous version.

`VCFsToCatalogs` can also deal with unfiltered VCFs. You can specify `filter.status` to only keep those variants that satisfied the criteria (e.g. specifying `filter.status` = "PASS" will only keep the variants with value "PASS" in the `FILTER` column in the original VCF/table).

If you want to write catalogs to CSV files and plot them to PDF once they are generated, you can try the new wrapper function 
`VCFsToZipFile`. This will create a zip archive containing all the catalogs CSV and PDF files together with a run-information file.

You can install the latest stable version of ICAMS from GitHub:
`remotes::install_github(repo = "steverozen/ICAMS", ref = "v2.3.1-branch")`

If you have other suggestion about this package or find any bug, please let us know. Thanks!

**Comment by ahwanpandey** [comment]
Hello,

I just installed the latest development version `ICAMS_3.0.0.9002` and the tool works flawlessly!

Thanks so much for putting the effort into making this available for us!

Best regards,
Ahwan

**Comment by jnh01** [comment]
@ahwanpandey 

Hi Ahwan,

Glad that the new version of ICAMS worked for you. 

As you were installing a development version, the interface of some new functions may change in the future. We will try to finalize that before the next CRAN release.

Thanks a lot for your previous suggestions. If you find any bug or have other suggestion about this package, please let us know!
