### ISSUE TITLE
Edge case in R/strandbias_functions.R/CalculatePValues()

### ISSUE THREAD

**Issue by JiaGengChang** [steverozen/ICAMS#6]
In the for loop, the conditional `if nrow(dt1) != 0` permits the `nrow(dt1) = 1` edge case.
But if `nrow(dt1) = 1`, then `summary(logit.model1)$coefficients` will only have one row. 
Trying to access the p-value with `summary(logit.model1)$coefficients[2,4]` will give subscript out of bounds error.
Suggested change:
the conditional `if nrow(dt1) != 0`  -> `if nrow(dt1) > 1`
Reason: minimum nrow(dt1) needed for second row p-value is 2.

**Comment by jnh01** [comment]
@JiaGengChang 
Thanks a lot for the suggestion. The problem actually occurs when there is only one unique `exp.value` in `dt1`, then this predictor variable will be dropped from the logistic regression model. In this case, calculating the p-value for the variable `exp.value` does not make sense.

There can be cases when more than one variant falls onto the same transcript region, hence they have the same `exp.value`. In this case, `nrow(dt1)` will be greater than 1, but still predictor `exp.value` will be dropped from the logistic model.

I have updated the code in master branch. If you find any other bug, please let us know. Thanks!
