### ISSUE TITLE
Does GetMutectVAF fits the situations of polyploids

### ISSUE THREAD

**Issue by hkhllyzh** [steverozen/ICAMS#9]
Hi,
I've been reading the codes of ICAMS and noticed that the GetMutectVAF function might only consider diploid alt, for it calculated vaf merely with vaf <- sum(x[c(2, 4)])/sum(x). Is that propose-designed or the whole toolkit was only meant to be used for diploid analyse?

**Comment by jnh01** [comment]
The GATK Mutect2 toolkit can work on non-diploid organisms, you may refer to this [post](https://gatk.broadinstitute.org/hc/en-us/articles/360035889691-Does-GATK-work-on-non-diploid-organisms-) for more details.

`GetMutectVAF` function can fit the situation of polyploids. Variant allele frequencies (VAFs) is a low level concept, the reads supporting the alternate alleles may come from diploid or polyploids. Calculation of the VAF does not need to know the ploidy of the sample.

**Comment by jnh01** [comment]
Hi @hkhllyzh,

Thanks for your question.

The GATK Mutect2 toolkit can work on non-diploid organisms, you may refer to this [post](https://gatk.broadinstitute.org/hc/en-us/articles/360035889691-Does-GATK-work-on-non-diploid-organisms-) for more details.

`GetMutectVAF` function can fit the situation of polyploids. Variant allele frequencies (VAFs) is a low level concept, the reads supporting the alternate alleles may come from diploid or polyploids. Calculation of the VAF does not need to know the ploidy of the sample. Hope this helps.
